CREATE TABLE IF NOT EXISTS EXECUTION_LOG
(
  ID             INT GENERATED ALWAYS AS IDENTITY,
  ENVIRONMENT    VARCHAR(250) NOT NULL,
  BATCH_NAME     VARCHAR(80) NOT NULL,
  BATCH_ID       VARCHAR(80) NOT NULL,
  EXECUTION_DATE TIMESTAMP NOT NULL,
  STATUS         VARCHAR(80) NOT NULL,
  CONSTRAINT PK_execution_log PRIMARY KEY (id)
);