spring:
  main:
    allow-bean-definition-overriding: true #i dont remember why but i think there is a bug with spring cloud and OAuth2ClientContext
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lastmile-database:5432/order-database
    username: postgres
    password: Lastmile2020!
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
  rabbitmq: 
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672
    virtual-host: /

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 180000
        readTimeout: 180000

hystrix:
  threadpool.default.coreSize: "20"
  threadpool.default.maxQueueSize: "500000"
  threadpool.default.keepAliveTimeMinutes: "2"
  threadpool.default.queueSizeRejectionThreshold: "500000"
  command:
    default:
      fallback.isolation.semaphore.maxConcurrentRequests: "20"
      execution:
        timeout:
          enabled: "false"
        isolation:
          strategy: "THREAD"
          thread:
            timeoutInMilliseconds: "180000"

lastmile:
  swagger:
    enabled: true
  ssl:
    enabled: false
  nearest:
    radius: 500000
  scheduler:
    future-date-offset: 30
  log:
    requests: true

logging:
  level:
    com.lastmile: INFO
    com.netflix: WARN
    org.apache.http: WARN
    org.hibernate.SQL.type.deor.sql: WARN
    org.springframework.web: WARN

rabbitmq:
  exchange:
    name: ${SPRING_PROFILES_ACTIVE:dev}
  routing-key:
    order-top-priority: orders.priority.top
    order-medium-priority: orders.priority.medium
    order-low-priority: orders.priority.low

google:
  api-key: <your_api_key>
  distance-matrix-api:
    base-url-string: "https://maps.googleapis.com/maps/api/distancematrix/json?"
    origins-url-string: "origins="
    destinations-url-string: "&destinations="
    key-url-string: "&key="
  geolocation-api:
    base-url-string: "https://maps.googleapis.com/maps/api/geocode/json?"
    latlang-url-string: "latlng="
    key-url-string: "&key="
    result-type-url-string: "&result_type=street_address"

cloud:
  aws:
    region: "us-east-2"
    credentials:
      accessKey: <your_access_key>
      secretKey: <your_secret_key>
    s3:
      bucketName: last-mile-storage
      endpointUrl: https://s3.us-east-2.amazonaws.com

twilio:
  # prod
  account-sid: <your_account_sid>
  auth-token: <your_auth_token>
  # test
  # account-sid: <your_account_sid>
  # auth-token: <your_auth_token>
  proxy:
    service-name: go-mile-local
    service-sid: <your_service_sid>
    session-timeout: 300 # session timeout defined as 5 minutes
  twiml:
    app-name: go-mile-local