CREATE TABLE IF NOT EXISTS orders (
    id serial PRIMARY KEY,
    order_identification varchar(255) not null,
    short_order_identification varchar(255) not null,
    order_external_identification varchar(255),
    requester_identification varchar(255) not null,
    requester_entity_name varchar(255) not null,
    requester_entity_type varchar(255) not null,
    requester_name varchar(255),
    requester_phone_number varchar(255) not null,
    requester_email varchar(255),
    requester_country varchar(255),
    requester_city varchar(255),
    requester_zip_code varchar(255),
    pickup_latitude float not null,
    pickup_longitude float not null,
    pickup_address varchar(255),
    destination_country varchar(255),
    destination_city varchar(255),
    destination_zip_code varchar(255),
    destination_latitude float not null,
    destination_longitude float not null,
    destination_address varchar(255),
    pickup_photo varchar(255),
    delivery_photo varchar(255),
    order_ext_voice_session varchar(255),
    order_ext_message_session varchar(255),
    status varchar(255) not null,
    priority varchar(255) not null,
    scheduled_date timestamp,
    assigned_driver varchar(255),
    delivery_fee_value numeric,
    driver_fee_value numeric,
    order_value numeric not null,
    order_type varchar(255) not null,
    order_rating int,
    estimated_distance int,
    packaging_eta int,
    pickup_eta int,
    delivery_eta int,
    effective_pickup_time int,
    effective_delivery_time int,
    owner_identification varchar(255),
    is_order_tracking_active boolean,
    payment_status varchar(255),
    driver_payment_status varchar(255),
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    UNIQUE(order_identification),
    UNIQUE(short_order_identification)
);