spring:
  main:
    allow-bean-definition-overriding: true #i dont remember why but i think there is a bug with spring cloud and OAuth2ClientContext
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lastmile-database:5432/driver-database
    username: postgres
    password: Lastmile2020!
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false

security:
  oauth2:
    client:
      clientId: driver-service
      clientSecret: 1234
      accessTokenUri: http://gateway-service:8080/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway-service:8080/uaa/user/current #zuul path to get current info about the context
      token-info-uri: http://gateway-service:8080/uaa/oauth/check_token #add this information

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 180000
        readTimeout: 180000

hystrix:
  threadpool.default.coreSize: "20"
  threadpool.default.maxQueueSize: "500000"
  threadpool.default.keepAliveTimeMinutes: "2"
  threadpool.default.queueSizeRejectionThreshold: "500000"
  command:
    default:
      fallback.isolation.semaphore.maxConcurrentRequests: "20"
      execution:
        timeout:
          enabled: "false"
        isolation:
          strategy: "THREAD"
          thread:
            timeoutInMilliseconds: "180000"

lastmile:
  swagger:
    enabled: true
  ssl:
    enabled: false
  log:
    requests: true

logging:
  level:
    com.lastmile: INFO
    com.netflix: WARN
    org.apache.http: INFO
    org.hibernate.SQL.type.deor.sql: INFO
    org.springframework.web: INFO

vehicles:
  api:
    url: "https://parseapi.back4app.com/classes/Carmodels_Car_Model_List?limit=2147483647"
    app-id: <your_app_id>
    api-key: <your_api_key>

cloud:
  aws:
    region: "us-east-2"
    credentials:
      accessKey: <your_access_key>
      secretKey: <your_secret_key>
    s3:
      bucketName: last-mile-storage
      endpointUrl: https://s3.us-east-2.amazonaws.com