CREATE TABLE IF NOT EXISTS accounts (
    id serial PRIMARY KEY,
    user_identification varchar(255) not null,
    account_type varchar(255) not null,
    username varchar(255) not null,
    email varchar(255),
    phone_number varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    birth_date date,
    active_address_id varchar(255),
    active_billing_address_id varchar(255),
    active_payment_details_id varchar(255),
    profile_picture varchar(255),
    role varchar(255) not null,
    is_active boolean not null,
    activation_code varchar(4),
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    UNIQUE(user_identification)
);