spring:
  main:
    allow-bean-definition-overriding: true #i dont remember why but i think there is a bug with spring cloud and OAuth2ClientContext
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lastmile-database:5432/account-database
    username: postgres
    password: Lastmile2020!
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
  rabbitmq: 
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672
    virtual-host: /

rabbitmq:
  exchange:
    name: ${SPRING_PROFILES_ACTIVE:local}
  routing-key:
    account-activation-sms: sms.account.activation
    account-activation-email: email.account.activation
    account-recovery-sms: sms.account.recovery
    account-recovery-email: email.account.recovery
    account-push-notification: push.account.notification
  sms:
    account-activation-template: account-activation
    code-length-key: 4
    code-length: code_length

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 1234
      accessTokenUri: http://auth-service:8081/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:8081/uaa/user/current
      token-info-uri: http://auth-service:8081/uaa/oauth/check_token

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 180000
        readTimeout: 180000

hystrix:
  threadpool.default.coreSize: "20"
  threadpool.default.maxQueueSize: "500000"
  threadpool.default.keepAliveTimeMinutes: "2"
  threadpool.default.queueSizeRejectionThreshold: "500000"
  command:
    default:
      fallback.isolation.semaphore.maxConcurrentRequests: "20"
      execution:
        timeout:
          enabled: "false"
        isolation:
          strategy: "THREAD"
          thread:
            timeoutInMilliseconds: "180000"

lastmile:
  swagger:
    enabled: true
  log:
    requests: true

logging:
  level:
    com.lastmile: INFO
    com.netflix: WARN
    org.apache.http: WARN
    org.hibernate.SQL.type.deor.sql: WARN
    org.springframework.web: WARN

authy:
  apikey: 72eZkW5QmiDfO7tTV9qvSk84JPbHID6K

cloud:
  aws:
    region: "us-east-2"
    credentials:
      accessKey: <your_access_key>
      secretKey: <your_secret_key>
    s3:
      bucketName: last-mile-storage
      endpointUrl: https://s3.us-east-2.amazonaws.com